[package]
name = "atomic-borrow"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/ChangeCaps/atomic-borrow"
description = "A simple atomic reference counter"
keywords = ["atomic", "reference", "counter", "borrow", "rc"]
readme = "README.md"
